apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security
  name: pod-reader
rules:
- apiGroups: [""] # "" означает apiGroup под именем core или legacy
  resources: ["pods"]
  verbs: ["get", "watch", "list"]