---
defaultRules:
  create: true
  rules:
    etcd: false 
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: devops
commonLabels:
  prometheus: devops
grafana:
  adminPassword: q1w2e3r4t5y6
