apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: vdoski/hipster-paymentservice:v0.0.1
          env:
            - name: "DISABLE_PROFILER"
              value: "True"
            - name: PORT
              value: "50051"