apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: my-first-pod # Название Pod
  labels: # Метки в формате key: value
    example_key: value
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: my-apache # Название контейнера
      image: vdoski/my_apache:v1.3 # Образ из которого создается контейнер